export const DUMMY_INFO = {
  venue: "St James' Park",
  spectators: 52122,
  refName: 'Robert Jones',
  refCountry: 'England',
  startDate: '18 May 2023',
};

export const DUMMY_STATS = [
  { stat: 'fouls', home: 17, away: 16 },
  { stat: 'throws', home: 23, away: 12 },
  {
    stat: 'offsides',
    home: 1,
    away: 2,
  },
  {
    stat: 'possession',
    home: 34,
    away: 66,
  },
];

export const DUMMY_SUMMARY = {
  homeHTScore: 2,
  awayHTScore: 0,
  homeFTScore: 4,
  awayFTScore: 1,
  firstHalfIncidents: [
    {
      minute: 22,
      team: 1,
      playerName: 'D.Undav',
      incident: 'ownGoal',
      score: [1, 0],
      hasAssisted: false,
    },
    {
      minute: 30,
      team: 1,
      playerName: 'B.Guimaraes',
      incident: 'yellowCard',
    },
    {
      minuteExtended: 2,
      minute: 45,
      team: 2,
      playerName: 'D.Undav',
      incident: 'yellowCard',
    },
    {
      minuteExtended: 3,
      minute: 45,
      team: 1,
      playerName: 'F.Schaer',
      incident: 'yellowCard',
    },
    {
      minuteExtended: 4,
      minute: 45,
      score: [2, 0],
      team: 1,
      hasAssisted: true,
      incident: 'goal',
      scorer: 'D.Burn',
      assister: 'K.Tripper',
    },
  ],
  secondHalfIncidents: [
    {
      minute: 51,
      team: 2,
      score: [2, 1],
      hasAssisted: true,
      scorer: 'D.Undav',
      assister: 'B.Gilmour',
    },
    {
      minute: 57,
      team: 2,
      playerName: 'P.Gross',
      incident: 'yellowCard',
    },
    {
      minute: 64,
      team: 2,
      playerName: 'A.Mac Allister',
      incident: 'yellowCard',
    },
    {
      minute: 80,
      team: 2,
      playerName: 'J.Paul van Hecke',
      incident: 'yellowCard',
    },
    {
      minute: 89,
      team: 1,
      score: [3, 1],
      hasAssisted: true,
      scorer: 'C.Wilson',
      assister: 'M.Almiron',
    },
    {
      minuteExtended: 1,
      minute: 90,
      team: 1,
      score: [4, 1],
      hasAssisted: true,
      scorer: 'B.Guimaraes',
      assister: 'C.Wilson',
    },
  ],
};

export const DUMMY_LINEUPS = {
  lineups: [
    {
      team: 1,
      players: [
        {
          playerId: '32354',
          playerName: 'Nick Pope',
          playerNumber: 22,
          formatPosition: '1:1',
        },
        {
          playerId: '30257',
          playerName: 'Keiran Trippier',
          playerNumber: 2,
          formatPosition: '2:1',
        },
        {
          playerId: '30259',
          playerName: 'Fabian Schar',
          playerNumber: 5,
          formatPosition: '2:2',
        },
        {
          playerId: '2103',
          playerName: 'Sven Botman',
          playerNumber: 4,
          formatPosition: '2:3',
        },
        {
          playerId: '30258',
          playerName: 'Dan Burn',
          playerNumber: 33,
          formatPosition: '2:4',
        },
        {
          playerId: '30275',
          playerName: 'Joseph Willock',
          playerNumber: 28,
          formatPosition: '3:1',
        },
        {
          playerId: '30279',
          playerName: 'Bruno Guimaraes',
          playerNumber: 39,
          formatPosition: '3:2',
        },
        {
          playerId: '30274',
          playerName: 'Joelinton',
          playerNumber: 7,
          formatPosition: '3:3',
        },
        {
          playerId: '30270',
          playerName: 'Miguel Almiron',
          playerNumber: 24,
          formatPosition: '4:1',
        },
        {
          playerId: '30261',
          playerName: 'Callum Wilson',
          playerNumber: 9,
          formatPosition: '4:2',
        },
        {
          playerId: '18647',
          playerName: 'Alexander Isak',
          playerNumber: 14,
          formatPosition: '4:3',
        },
        {
          playerId: '30253',
          playerName: 'Martin Dubravka',
          formatPosition: 'substitutePlayer',
          playerNumber: 1,
        },
        {
          playerId: '30266',
          playerName: 'Paul Dummett',
          formatPosition: 'substitutePlayer',
          playerNumber: 3,
        },
        {
          playerId: '30276',
          playerName: 'Jamal Lewis',
          formatPosition: 'substitutePlayer',
          playerNumber: 12,
        },
        {
          playerId: '30272',
          playerName: 'Matt Target',
          formatPosition: 'substitutePlayer',
          playerNumber: 13,
        },
        {
          playerId: '30268',
          playerName: 'Javi Manquillo',
          formatPosition: 'substitutePlayer',
          playerNumber: 19,
        },
        {
          playerId: '33655',
          playerName: 'Anthony Gordon',
          formatPosition: 'substitutePlayer',
          playerNumber: 8,
        },
      ],
      formation: [4, 3, 3],
      coach: 'Eddie Howe',
    },
    {
      team: 2,
      PLAYERS: [
        {
          playerId: '21168',
          playerName: 'Jason Steele',
          playerNumber: 23,
          formatPosition: '1:1',
        },
        {
          playerId: '21192',
          playerName: 'Jason Steele',
          playerNumber: 25,
          formatPosition: '2:1',
        },
        {
          playerId: '21172',
          playerName: 'Jason Steele',
          playerNumber: 5,
          formatPosition: '2:2',
        },
        {
          playerId: '32061',
          playerName: 'Jan Paul Van Hecke ',
          playerNumber: 29,
          formatPosition: '2:3',
        },
        {
          playerId: '18516',
          playerName: 'Jason Steele',
          playerNumber: 30,
          formatPosition: '2:4',
        },
        {
          playerId: '21170',
          playerName: 'Jason Gross',
          playerNumber: 13,
          formatPosition: '3:1',
        },
        {
          playerId: '15329',
          playerName: 'Billy Steele',
          playerNumber: 27,
          formatPosition: '3:2',
        },
        {
          playerId: '24871',
          playerName: 'Valentin Steele',
          playerNumber: 40,
          formatPosition: '4:1',
        },
        {
          playerId: '34076',
          playerName: 'Deniz Undav',
          playerNumber: 21,
          PLAYER_POSITION_ACTUAL: 3,
          formatPosition: '4:2',
        },
        {
          playerId: '33258',
          playerName: 'Jason Mitoma',
          playerNumber: 22,
          PLAYER_POSITION_ACTUAL: 3,
          formatPosition: '4:3',
        },
        {
          playerId: '21169',
          playerName: 'Jason Welbeck',
          playerNumber: 18,
          PLAYER_POSITION_ACTUAL: 4,
          formatPosition: '5:1',
        },
        {
          playerId: '21182',
          playerName: 'Jason Steele',
          formatPosition: 'substitutePlayer',
          playerNumber: 38,
        },
        {
          playerId: '21196',
          playerName: 'Jason offiah',
          formatPosition: 'substitutePlayer',
          playerNumber: 42,
        },
        {
          playerId: '18204',
          playerName: 'Imari Steele',
          formatPosition: 'substitutePlayer',
          playerNumber: 66,
        },
        {
          playerId: '21185',
          playerName: 'Alexis Mac Allister',
          formatPosition: 'substitutePlayer',
          playerNumber: 10,
        },
      ],
      formation: [4, 2, 3, 1],
      coach: 'Roberto De Zebri',
    },
  ],
  subs: {
    2: [
      {
        minute: 56,
        NAME: 2,
        subOutPlayerId: '15329',
        subOutPlayerName: 'Billy Gilmour',
        subInPlayerId: '21185',
        subInPlayerName: 'Alexis Mac Allister',
      },
      {
        minute: 56,
        NAME: 2,
        subOutPlayerId: '24871',
        subOutPlayerName: 'Facundo Buonanotte',
        subInPlayerId: '33595',
        subInPlayerName: 'Julio Enciso',
      },
      {
        minuteExtended: 5,
        minute: 90,
        NAME: 1,
        subOutPlayerId: '30274',
        subOutPlayerName: 'Joelinton',
        subInPlayerId: '30272',
        subInPlayerName: 'Matt Target',
      },
      {
        minuteExtended: 5,
        minute: 90,
        NAME: 1,
        subOutPlayerId: '30257',
        subOutPlayerName: 'Kieran Trippier',
        subInPlayerId: '30268',
        subInPlayerName: 'Javi Manquillo',
      },
    ],
  },
};
export const DUMMY_TABLE = [
  {
    position: 1,
    name: 'Barcelona',
    group: null,
    teamId: '2911',
    teamImageUrl: 'https://lsm-static-prod.livescore.com/medium/enet/8634.png',
    played: 36,
    wins: 27,
    draws: 4,
    loses: 5,
    GF: 66,
    GA: 18,
    GD: 48,
    points: 85,
  },
  {
    position: 2,
    name: 'Atletico Madrid',
    group: null,
    teamId: '2912',
    teamImageUrl: 'https://lsm-static-prod.livescore.com/medium/enet/9906.png',
    played: 35,
    wins: 22,
    draws: 6,
    loses: 7,
    GF: 63,
    GA: 27,
    GD: 36,
    points: 72,
  },
  {
    position: 3,
    name: 'Real Madrid',
    group: null,
    teamId: '4009',
    teamImageUrl: 'https://lsm-static-prod.livescore.com/medium/enet/8633.png',
    played: 35,
    wins: 22,
    draws: 5,
    loses: 8,
    GF: 70,
    GA: 33,
    GD: 37,
    points: 71,
  },
  {
    position: 4,
    name: 'Real Sociedad',
    group: null,
    teamId: '4169',
    teamImageUrl: 'https://lsm-static-prod.livescore.com/medium/enet/8560.png',
    played: 36,
    wins: 20,
    draws: 8,
    loses: 8,
    GF: 48,
    GA: 32,
    GD: 16,
    points: 68,
  },
  {
    position: 5,
    name: 'Villarreal',
    group: null,
    teamId: '3608',
    teamImageUrl: 'https://lsm-static-prod.livescore.com/medium/enet/10205.png',
    played: 35,
    wins: 18,
    draws: 6,
    loses: 11,
    GF: 54,
    GA: 36,
    GD: 18,
    points: 60,
  },
  {
    position: 6,
    name: 'Real Betis',
    group: null,
    teamId: '3352',
    teamImageUrl: 'https://lsm-static-prod.livescore.com/medium/enet/8603.png',
    played: 35,
    wins: 16,
    draws: 8,
    loses: 11,
    GF: 43,
    GA: 38,
    GD: 5,
    points: 56,
  },
  {
    position: 7,
    name: 'Athletic Bilbao',
    group: null,
    teamId: '3408',
    teamImageUrl: 'https://lsm-static-prod.livescore.com/medium/enet/8315.png',
    played: 35,
    wins: 14,
    draws: 8,
    loses: 13,
    GF: 46,
    GA: 39,
    GD: 7,
    points: 50,
  },
  {
    position: 8,
    name: 'Girona',
    group: null,
    teamId: '3586',
    teamImageUrl: 'https://lsm-static-prod.livescore.com/medium/enet/7732.png',
    played: 36,
    wins: 13,
    draws: 10,
    loses: 13,
    GF: 56,
    GA: 51,
    GD: 5,
    points: 49,
  },
  {
    position: 9,
    name: 'Sevilla',
    group: null,
    teamId: '12634',
    teamImageUrl: 'https://lsm-static-prod.livescore.com/medium/enet/8302.png',
    played: 35,
    wins: 13,
    draws: 9,
    loses: 13,
    GF: 44,
    GA: 49,
    GD: -5,
    points: 48,
  },
  {
    position: 10,
    name: 'Osasuna',
    group: null,
    teamId: '463',
    teamImageUrl: 'https://lsm-static-prod.livescore.com/medium/enet/8371.png',
    played: 35,
    wins: 13,
    draws: 8,
    loses: 14,
    GF: 32,
    GA: 39,
    GD: -7,
    points: 47,
  },
  {
    position: 11,
    name: 'Rayo Vallecano',
    group: null,
    teamId: '4253',
    teamImageUrl: 'https://lsm-static-prod.livescore.com/medium/enet/8370.png',
    played: 35,
    wins: 12,
    draws: 10,
    loses: 13,
    GF: 42,
    GA: 47,
    GD: -5,
    points: 46,
  },
  {
    position: 12,
    name: 'Mallorca',
    group: null,
    teamId: '500',
    teamImageUrl: 'https://lsm-static-prod.livescore.com/medium/enet/8661.png',
    played: 35,
    wins: 12,
    draws: 8,
    loses: 15,
    GF: 33,
    GA: 40,
    GD: -7,
    points: 44,
  },
  {
    position: 13,
    name: 'Valencia',
    group: null,
    teamId: '4008',
    teamImageUrl: 'https://lsm-static-prod.livescore.com/medium/enet/10267.png',
    played: 35,
    wins: 11,
    draws: 7,
    loses: 17,
    GF: 39,
    GA: 41,
    GD: -2,
    points: 40,
  },
  {
    position: 14,
    name: 'Celta Vigo',
    group: null,
    teamId: '4162',
    teamImageUrl: 'https://lsm-static-prod.livescore.com/medium/enet/9910.png',
    played: 36,
    wins: 10,
    draws: 10,
    loses: 16,
    GF: 41,
    GA: 51,
    GD: -10,
    points: 40,
  },
  {
    position: 15,
    name: 'Almeria',
    group: null,
    teamId: '4518',
    teamImageUrl: 'https://lsm-static-prod.livescore.com/medium/enet/9865.png',
    played: 36,
    wins: 11,
    draws: 6,
    loses: 19,
    GF: 46,
    GA: 62,
    GD: -16,
    points: 39,
  },
  {
    position: 16,
    name: 'Cadiz',
    group: null,
    teamId: '3434',
    teamImageUrl: 'https://lsm-static-prod.livescore.com/medium/enet/8385.png',
    played: 35,
    wins: 9,
    draws: 11,
    loses: 15,
    GF: 28,
    GA: 50,
    GD: -22,
    points: 38,
  },
  {
    position: 17,
    name: 'Real Valladolid',
    group: null,
    teamId: '3658',
    teamImageUrl: 'https://lsm-static-prod.livescore.com/medium/enet/10281.png',
    played: 36,
    wins: 11,
    draws: 5,
    loses: 20,
    GF: 33,
    GA: 63,
    GD: -30,
    points: 38,
  },
  {
    position: 18,
    name: 'Getafe',
    group: null,
    teamId: '3379',
    teamImageUrl: 'https://lsm-static-prod.livescore.com/medium/enet/8305.png',
    played: 35,
    wins: 8,
    draws: 11,
    loses: 16,
    GF: 31,
    GA: 44,
    GD: -13,
    points: 35,
  },
  {
    position: 19,
    name: 'Espanyol',
    group: null,
    teamId: '12635',
    teamImageUrl: 'https://lsm-static-prod.livescore.com/medium/enet/8558.png',
    played: 35,
    wins: 8,
    draws: 10,
    loses: 17,
    GF: 44,
    GA: 61,
    GD: -17,
    points: 34,
  },
  {
    position: 20,
    name: 'Elche',
    group: null,
    teamId: '3622',
    teamImageUrl: 'https://lsm-static-prod.livescore.com/medium/enet/10268.png',
    played: 35,
    wins: 4,
    draws: 8,
    loses: 23,
    GF: 27,
    GA: 65,
    GD: -38,
    points: 20,
  },
];
