export const DUMMY_LINEUPS = {
  lineups: [
    {
      team: 1,
      players: [
        {
          playerId: '32354',
          playerName: 'Nick Pope',
          playerNumber: 22,
          formatPosition: '1:1',
        },
        {
          playerId: '30257',
          playerName: 'Keiran Trippier',
          playerNumber: 2,
          formatPosition: '2:1',
        },
        {
          playerId: '30259',
          playerName: 'Fabian Schar',
          playerNumber: 5,
          formatPosition: '2:2',
        },
        {
          playerId: '2103',
          playerName: 'Sven Botman',
          playerNumber: 4,
          formatPosition: '2:3',
        },
        {
          playerId: '30258',
          playerName: 'Dan Burn',
          playerNumber: 33,
          formatPosition: '3:1',
        },
        {
          playerId: '30275',
          playerName: 'Joseph Willock',
          playerNumber: 28,
          formatPosition: '3:2',
        },
        {
          playerId: '30279',
          playerName: 'Bruno Guimaraes',
          playerNumber: 39,
          formatPosition: '3:3',
        },
        {
          playerId: '30274',
          playerName: 'Joelinton',
          playerNumber: 7,
          formatPosition: '3:4',
        },
        {
          playerId: '30270',
          playerName: 'Miguel Almiron',
          playerNumber: 24,
          formatPosition: '3:5',
        },
        {
          playerId: '30261',
          playerName: 'Callum Wilson',
          playerNumber: 9,
          formatPosition: '4:1',
        },
        {
          playerId: '18647',
          playerName: 'Alexander Isak',
          playerNumber: 14,
          formatPosition: '4:2',
        },
        {
          playerId: '30253',
          playerName: 'Martin Dubravka',
          formatPosition: 'substitutePlayer',
          playerNumber: 1,
        },
        {
          playerId: '30266',
          playerName: 'Paul Dummett',
          formatPosition: 'substitutePlayer',
          playerNumber: 3,
        },
        {
          playerId: '30276',
          playerName: 'Jamal Lewis',
          formatPosition: 'substitutePlayer',
          playerNumber: 12,
        },
        {
          playerId: '30272',
          playerName: 'Matt Target',
          formatPosition: 'substitutePlayer',
          playerNumber: 13,
        },
        {
          playerId: '30268',
          playerName: 'Javi Manquillo',
          formatPosition: 'substitutePlayer',
          playerNumber: 19,
        },
        {
          playerId: '33655',
          playerName: 'Anthony Gordon',
          formatPosition: 'substitutePlayer',
          playerNumber: 8,
        },
      ],
      formation: [4, 3, 3],
      coach: 'Eddie Howe',
    },
    {
      team: 2,
      players: [
        {
          playerId: '21168',
          playerName: 'Jason Steele',
          playerNumber: 23,
          formatPosition: '1:1',
        },
        {
          playerId: '21192',
          playerName: 'Jason Steele',
          playerNumber: 25,
          formatPosition: '2:1',
        },
        {
          playerId: '21172',
          playerName: 'Jason Steele',
          playerNumber: 5,
          formatPosition: '2:2',
        },
        {
          playerId: '32061',
          playerName: 'Jan Paul Van Hecke ',
          playerNumber: 29,
          formatPosition: '2:3',
        },
        {
          playerId: '18516',
          playerName: 'Jason Steele',
          playerNumber: 30,
          formatPosition: '2:4',
        },
        {
          playerId: '21170',
          playerName: 'Jason Gross',
          playerNumber: 13,
          formatPosition: '3:1',
        },
        {
          playerId: '15329',
          playerName: 'Billy Steele',
          playerNumber: 27,
          formatPosition: '3:2',
        },
        {
          playerId: '24871',
          playerName: 'Valentin Steele',
          playerNumber: 40,
          formatPosition: '4:1',
        },
        {
          playerId: '34076',
          playerName: 'Deniz Undav',
          playerNumber: 21,
          PLAYER_POSITION_ACTUAL: 3,
          formatPosition: '4:2',
        },
        {
          playerId: '33258',
          playerName: 'Jason Mitoma',
          playerNumber: 22,
          PLAYER_POSITION_ACTUAL: 3,
          formatPosition: '4:3',
        },
        {
          playerId: '21169',
          playerName: 'Jason Welbeck',
          playerNumber: 18,
          PLAYER_POSITION_ACTUAL: 4,
          formatPosition: '5:1',
        },
        {
          playerId: '21182',
          playerName: 'Jason Steele',
          formatPosition: 'substitutePlayer',
          playerNumber: 38,
        },
        {
          playerId: '21196',
          playerName: 'Jason offiah',
          formatPosition: 'substitutePlayer',
          playerNumber: 42,
        },
        {
          playerId: '18204',
          playerName: 'Imari Steele',
          formatPosition: 'substitutePlayer',
          playerNumber: 66,
        },
        {
          playerId: '21185',
          playerName: 'Alexis Mac Allister',
          formatPosition: 'substitutePlayer',
          playerNumber: 10,
        },
      ],
      formation: [4, 2, 3, 1],
      coach: 'Roberto De Zebri',
    },
  ],
  subs: {
    1: [
      {
        minuteExtended: 5,
        minute: 45,
        team: 1,
        subOutPlayerId: '3274',
        subOutPlayerName: 'Joelinto',
        subInPlayerId: '30272',
        subInPlayerName: 'Matt arget',
      },
    ],
    2: [
      {
        minute: 56,
        team: 2,
        subOutPlayerId: '15329',
        subOutPlayerName: 'Billy Gilmour',
        subInPlayerId: '21185',
        subInPlayerName: 'Alexis Mac Allister',
      },
      {
        minute: 56,
        team: 2,
        subOutPlayerId: '24871',
        subOutPlayerName: 'Facundo Buonanotte',
        subInPlayerId: '33595',
        subInPlayerName: 'Julio Enciso',
      },
      {
        minuteExtended: 5,
        minute: 90,
        team: 1,
        subOutPlayerId: '30274',
        subOutPlayerName: 'Joelinton',
        subInPlayerId: '30272',
        subInPlayerName: 'Matt Target',
      },
      {
        minuteExtended: 5,
        minute: 90,
        team: 1,
        subOutPlayerId: '30257',
        subOutPlayerName: 'Kieran Trippier',
        subInPlayerId: '30268',
        subInPlayerName: 'Javi Manquillo',
      },
    ],
  },
};
